version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      RDS_URL: "username:password@tcp(db:3306)/dbname"
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbname
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: